const Settings = require("../../Helper's/Settings.json")
const AutoRepy = require("../../Helper's/AutoRepy")
const sunucuVeri = require("../../Helper's/MongooseSchema/_setup")
const { MessageEmbed, Discord } = require("discord.js");
module.exports = { name: "yardım", aliases: ["komutlar"],
    execute: async (client, message, args, ClientEmbed, FlatEmbed) => { 
    let Server = await sunucuVeri.findOne({ guildID: client.guilds.cache.get(Settings.guildID) })
    if(!message.member.permissions.has("8") && !Server.yönetimRoles.some(rol => message.member.roles.cache.has(rol)) &&!Server.ownerRoles.some(rol => message.member.roles.cache.has(rol))) return message.reply(AutoReply.YetersizYetki)
    let Embed = new MessageEmbed().setFooter(`${Settings["Client.Bot.Footer"]}`).setAuthor(message.guild.name, message.guild.iconURL({dynamic: true})).setColor("RANDOM");
    message.channel.send({ embeds: [Embed.setDescription(`Moderasyon Botumuzda toplamda \`${client.commands.size}\` komut bulunmaktadır.\`\`\`Client-Owner Command's\`\`\`\n${client.commands.filter(cmd => cmd.category && cmd.category && cmd.category === "Client-owner").map(cmd => `\`${Settings.Prefix}${cmd.name}\` ${cmd.desc}.`).join("\n")}\`\`\`Owner Command's\`\`\`\n${client.commands.filter(cmd => cmd.category && cmd.category && cmd.category === "Owner").map(cmd => `\`${Settings.Prefix}${cmd.name}\` ${cmd.desc}.`).join("\n")}\`\`\`Co-Owner Command's\`\`\`\n${client.commands.filter(cmd => cmd.category && cmd.category && cmd.category === "Co-owner").map(cmd => `\`${Settings.Prefix}${cmd.name}\` ${cmd.desc}.`).join("\n")}\`\`\`Penal Command's\`\`\`\n${client.commands.filter(cmd => cmd.category && cmd.category && cmd.category === "Penal").map(cmd => `\`${Settings.Prefix}${cmd.name}\` ${cmd.desc}.`).join("\n")}\`\`\`Register Command's\`\`\`\n${client.commands.filter(cmd => cmd.category && cmd.category && cmd.category === "Register").map(cmd => `\`${Settings.Prefix}${cmd.name}\` ${cmd.desc}.`).join("\n")}\`\`\`Staff Command's\`\`\`\n${client.commands.filter(cmd => cmd.category && cmd.category && cmd.category === "Staff").map(cmd => `\`${Settings.Prefix}${cmd.name}\` ${cmd.desc}.`).join("\n")}\`\`\`User Command's\`\`\`\n${client.commands.filter(cmd => cmd.category && cmd.category && cmd.category === "User").map(cmd => `\`${Settings.Prefix}${cmd.name}\` ${cmd.desc}.`).join("\n")}`)] })}}